spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082

application:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  swagger:
    enabled: true